/// Flutter icons Medal
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Medal
///      fonts:
///       - asset: fonts/Medal.ttf
///
///
///
import 'package:flutter/widgets.dart';

class Medal {
  Medal._();

  static const _kFontFam = 'Medal';
  static const String? _kFontPkg = null;

  static const IconData medal =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
