name: Test PR and Push
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  
jobs:
  build:
    name: Test Example
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
    - run: flutter pub get
      working-directory: example
    - name: Run Dart Analyzer
      run: flutter analyze
      working-directory: example
    - name: Run tests
      run: flutter test --coverage
      working-directory: example